name = "lwt"
description = "Light-weight Threading Library implementing Ada 2022 parallel features"
version = "1.2.0"

authors = ["S. Tucker Taft"]
maintainers = ["S. Tucker Taft <taft@adacore.com>"]
maintainers-logins = ["sttaft"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/parasail-lang/parasail/tree/main/lwt"
tags = ["ada2022", "parallel", "openmp"]

[[depends-on]]
[depends-on."case(os)".windows]
libgomp = "*"


[origin]
commit = "fedb90bac6225cebfd849d45f2937f66f423649e"
subdir = "./lwt/"
url = "git+https://github.com/parasail-lang/parasail.git"

