description = "GNU Binutils BFD libraries"
name = "libbfd"

maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["binutils-dev"]

# No binutils on Windows and MacOS
[external.available.'case(os)']
linux = true
'...' = false

