name = "tb6612_driver"
description = "Driver for the TB6612 dual DC motor driver IC."
version = "0.1.0"

authors = ["Karsten Lueth"]
maintainers = ["Karsten Lueth <kl@kloc-consulting.de>"]
maintainers-logins = ["KLOC-Karsten"]
licenses = "BSD-3-Clause"
website = "https://gitlab.com/KLOC-Karsten/tb6612_driver"
tags = ["motor", "driver", "embedded", "hal"]

[[depends-on]]
hal = "^1.0.0"

[origin]
commit = "e7bf4eb9d571d1cafa50dd6e83c503fd98fed119"
url = "git+https://gitlab.com/KLOC-Karsten/tb6612_driver.git"

